### ISSUE TITLE
MSVCR120

### ISSUE THREAD

**Issue by sulikale** [Dead2/xmr-stak-cpu#1]
_FYI_
E31220 @ WinSrv2008R2
xmr-stak by Fireice works, but your version x64 give me MSVCR120.dll error.
C++ redistributables 2017 reinstalled. I can't install v.2015 for test, but anyway it will be step back.

_mingw legacy/modern works, but slow_

**Comment by Dead2** [comment]
The crypto-libraries need vcredist 2013, the miner itself requires 2017.
